### PR TITLE
Feature wednesday message now includes picture

### PR DESCRIPTION
**Pull request by shubheshdwivedi**
# Added images for each Wednesday response, hosted the images on imgur.
Wednesday -
image
---
Tuesday -
image
---
Thursday -
image
---
Any other day -
image

### CODE REVIEW

**Comment by tomassirio** [comment]
OH MY GOD I LOVE IT

**Comment by shubheshdwivedi** [comment]
Thanks :)

**Comment by tomassirio** [comment]
Hey @shubheshdwivedi join us in the [discord channel](https://discord.gg/wtrfB7). I really liked that change, it brought me a really good chuckle

**Comment by shubheshdwivedi** [comment]
Joined!

**Pull request merged**
